name: sociogram
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  intl_phone_number_field: ^0.1.7
  otp_text_field: ^1.1.3
  calendar_date_picker2: ^0.5.2
  get_cli: ^1.8.1
  get: any
  image_picker: ^1.0.0
  syncfusion_flutter_charts: ^22.1.37
  flutter_rating_bar: ^4.0.1
  getwidget: ^3.1.1
  story_view: ^0.16.5
  url_launcher: ^6.1.12
  flutter_share: ^2.0.0


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Urbanist
      fonts:
        - asset: asset/Urbanist-Black.ttf
    - family: Urbanist-medium
      fonts:
        - asset: asset/Urbanist-Medium.ttf
    - family: Urbanist-semibold
      fonts:
        - asset: asset/Urbanist-SemiBold.ttf
    - family: Urbanist-bold
      fonts:
        - asset: asset/Urbanist-Bold.ttf
    - family: Urbanist-regular
      fonts:
        - asset: asset/Urbanist-Regular.ttf
